### ISSUE TITLE
Spike: Research options for scheduling EE

### ISSUE THREAD

**Issue by rileydakota** [jonrau1/ElectricEye#104]
Placeholder issue for discussion/research around the best mechanism to schedule ElectricEye container jobs to run per Account/Region.

**Comment by jonrau1** [comment]
From discussion, one way would be to use the container runtime itself to Assume the Role, write out new ENV VARs and then run ElectricEye for the downstream scheduled Tasks

Other issue to figure out is swapping back to the original role to upload findings to DynamoDB

**Comment by jonrau1** [comment]
@rileydakota - began to build out a way to assume role credentials and pass along a session object. I will need to edit every auditor to use the session object to create Boto3 Clients & Resources but I THINK that this is the better way.

By the time you see this I'm sure I'll have 143104134 more commits due to breaking shit but here it is https://github.com/jonrau1/ElectricEye/commit/45791d454787e7fee079ebec594d23ea46a2c3fb

**Comment by rileydakota** [comment]
@jonrau1 Just compiling some implementation ideas here:

1) Long lived "Scheduler" Container in ECS
 - Tenants, Role Arns, and associated accounts/regions, etc stored in Dynamo
 -  Scheduler reads DynamoDB on interval
 -  Could use Python [schedule](https://schedule.readthedocs.io/en/stable/) library or similar
 -  Unique Accounts/Regions are registered into our schedule
 -  Scheduler preforms a "fire and forget" to launch needed ECS tasks that execute auditor/controller.py injecting the appropriate region and role
 -  Eventually that DynamoDB table could be fronted with an API that allows onboarding

The scheduler documentation actually calls out some things that might be annoying long term however (from https://schedule.readthedocs.io/en/stable/index.html#when-not-to-use-schedule). Of the four listed items - "Concurrent execution (multiple threads)" could cause problems at larger scales, but early on should be mitigated by threads and performing "fire and forget" when launching the auditors so the scheduler doesn't wait for tasks to complete, (maybe only confirms their launch?).


2) (I know I know) Utilize [Amazon EventBridge Scheduler](https://aws.amazon.com/blogs/compute/introducing-amazon-eventbridge-scheduler/)
- Instead of a dynamoDB table, could just abstract away [CreateSchedule](https://docs.aws.amazon.com/scheduler/latest/APIReference/API_CreateSchedule.html) and [CreateScheduleGroup](https://docs.aws.amazon.com/scheduler/latest/APIReference/API_CreateScheduleGroup.html) as mechanisms for tenancy and AWS accounts/regions
- EventBridge Scheduler would kick off tasks for us in the same manner as above, kicking off ECS tasks by passing in the needed properties (region, account, role name/arn) via environment variables
- Limits seem tolerable for early/mid tier: https://docs.aws.amazon.com/scheduler/latest/UserGuide/scheduler-quotas.html
- 500 Schedule Groups/region (soft), 1,000,000 schedules/region (soft)

Downsides to this approaching being the painpoints/testability of AWS EventBridge, and some additional integration would be needed, as it looks neither the ECS [Templated Targets](https://docs.aws.amazon.com/scheduler/latest/UserGuide/managing-targets-templated.html) or [Universal Targets](https://docs.aws.amazon.com/scheduler/latest/UserGuide/managing-targets-universal.html) allow for an easy method of providing environment variables to the ECS task. Likely a queue, bus, lambda or some other intermediary thing.

Ultimately - I guess it depends on where we want to offload our complexity to? Eventbridge Scheduler or a long lived Python container in ECS that polls dynamo?

**Comment by jonrau1** [comment]
@rileydakota looks like Python `schedule` wants to receive something back given their drawbacks and considerations around concurrency. which should not really matter, as long as the jobs are successful -- i.e, they don't exit with anything other than a 0 or whatever ECS fires

My idea would be as part of onboarding would just be a Lambda + EventBridge Scheduled Rule that wakes the Lambda up, it reads a Map of Regions and a Map of Accounts from DDB and then loops that to call ECS RunTask with a minimized version of the ElectricEye Container

Just need to change the entrypoint `CMD` to accept the different args for Account, RoleName and Region as needed which are passed from ENVs, as RunTask allows you to call overrides into the Task Definition

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ecs/client/run_task.html

```python
overrides={
    'containerOverrides': [
        {
            'name': 'string',
            'command': [
                'string',
            ],
            'environment': [
                {
                    'name': 'string',
                    'value': 'string'
                },
            ],
            'environmentFiles': [
                {
                    'value': 'string',
                    'type': 's3'
                },
            ],
            'cpu': 123,
            'memory': 123,
            'memoryReservation': 123,
            'resourceRequirements': [
                {
                    'value': 'string',
                    'type': 'GPU'|'InferenceAccelerator'
                },
            ]
        },
    ],
    'cpu': 'string',
    'inferenceAcceleratorOverrides': [
        {
            'deviceName': 'string',
            'deviceType': 'string'
        },
    ],
    'executionRoleArn': 'string',
    'memory': 'string',
    'taskRoleArn': 'string',
    'ephemeralStorage': {
        'sizeInGiB': 123
    }
},
```

The only concern I'd have longer term is WCUs into DDB, which albeit, is pretty low. Can write batches and make use of the "chunking" function within the SecHub writer - I cannot imagine many findings going in overall and the DDB Writer chops down ASFF considerably into native types without much silliness. Unless someone had a massive tenant with 100s of accounts each with multiple Regions - can always have a dynamic pause in between the launches as long as it doesn't overrun the Lambda 15 min

I also have a `Delay` flag built into the controller that can be repurposed into the DDB writer to add a few seconds delays in between writes as a lazy way to avoid throttles. But 3000 WCUs is pretty hard to overrun - that's 6000MB or some shit on concurrent writes into DDB and the finding IDs are long and unique enough to utilize hash space effectively and could always be artifically lengthened as well with a nonce & tenant GUID

**Comment by jonrau1** [comment]
Heads up @rileydakota I merged what I was doing in SSPM into Backend branch -- I did not update the documentation on usage just yet
