### ISSUE TITLE
Opensearch Audit Boto Parameter Validation Issue 

### ISSUE THREAD

**Issue by rpatkialbelli** [jonrau1/ElectricEye#188]
**Describe the bug**
Amazon_ElasticsearchService_Auditor throws errors around parameter validation. Following error is encountered:
_botocore.exceptions.ParamValidationError: Parameter validation failed: Invalid type for parameter DomainName, value: {'DomainName': 'unified-logging-es-prod', 'EngineType': 'OpenSearch'}, type: <class 'dict'>, valid types: <class 'str'>"_

The error is actually caused by the way the describe_elasticsearch_domain method is called within the describe_es_os_domains function.
The describe_elasticsearch_domain method expects the DomainName parameter to be passed as a string, not as a dictionary. However, in your case, it seems that the domain variable (which is an element in the list returned by elasticsearch.list_domain_names()["DomainNames"]) is a dictionary containing DomainName and EngineType keys.
To resolve the issue, you should modify the describe_es_os_domains function to extract the DomainName string from the domain dictionary before passing it to the describe_elasticsearch_domain method.

The following code change fixes the issue:

```
def describe_es_os_domains(cache, session):
    response = cache.get("list_domain_names")
    if response:
        return response
    
    elasticsearch = session.client("es")
    domainDetails = []

    for domain in elasticsearch.list_domain_names()["DomainNames"]:
        domainName = domain["DomainName"]
        domainDetails.append(
            elasticsearch.describe_elasticsearch_domain(
                DomainName=domainName
            )
        )

    cache["list_domain_names"] = domainDetails
    return cache["list_domain_names"]

```

**Comment by jonrau1** [comment]
Damn, rookie skill issue.

Thanks - change committed into the salesforce_v1 branch
