### ISSUE TITLE
[PFR] Upgrade all Terraform scripts to v0.12.x

### ISSUE THREAD

**Issue by jonrau1** [jonrau1/ElectricEye#35]
**Story**
As a user of ElectricEye I want all Terraform config files writen in v0.12.x so that I can ensure I can use the latest AWS Provider and potentially scan my the files in CI/CD with some awesome SAST tool

**Definition of Done**
- All Terraform is upgraded to 0.12.x

**Nice to Have**
N/A

**Additional Information**
N/A

**Comment by mourackb** [comment]
I can assist with that. There is a branch where this is being developed?

**Comment by jonrau1** [comment]
Hey @mourackb I just opened a new branch `terraform-12` for any development work. https://github.com/jonrau1/ElectricEye/tree/terraform-12

**Comment by jonrau1** [comment]
Core module TF upgraded with #39
