### ISSUE TITLE
[PFR] Onboard additional checks to ElectricEye v2.0

### ISSUE THREAD

**Issue by jonrau1** [jonrau1/ElectricEye#36]
**Story**
As a user of ElectricEye I want to have new checks for other AWS services onboarded into ElectricEye v2.0 so that I can use the new framework for checking the compliance on services such as Global Accelerator so that I can assess my cloud security posture and take action. **note** some of these are the deferred checks from #23 

**Definition of Done**
- All 3 IAM permissions (CFN, TF, Standalone) are updated to include new required permissions
- Readme updated for total count of auditors/checks and the new checks are added
- All new checks mapped to Compliance.RelatedRequirements checks
- The following checks are added:
    - Global Accelerator: Check the healthiness of Endpoint Groups by Endpoint ID using DescribeEndpointGroup API - if `HealthState` = `UNHEALTHY` it fails the check. The ASFF Resource.Type should be `AwsGlobalAcceleratorEndpoint`
    - Global Aceelerator: Check if GA has access logging enabled by using the DescribeAcceleratorAttributes - if `FlowLogsEnabled` = `False` it fails the check. The ASFF Resource.Type should be `AwsGlobalAcceleratorAccelerator` (yes, it's annoying, yes it's a req)
    - Security Shared Services: Check if Maciev2 is enabled by querying the GetMacieSession API. If it fails there is likely not a session enabled in that region. The ASFF Resource.Type should be scoped to `AwsAccount` and added to the Security/SSVC Auditor
    - EC2 Image Builder: Check if tests for image builder pipelines are enabled using the GetImagePipeline API - if they are disabled the check fails. The ASFF Resource.Type should be `AwsEc2ImageBuilderPipeline`.
    - EC2 Image Builder: Check if the image recipes encrypt EBS volumes by default - if `ebs.encrypted` = `False` it fails the check. The ASFF Resource.Type should be `AwsEc2ImageBuilderRecipe`.
    - Resource Access Manager: Check if any RAM shares are Failed by using the GetResourceShares API. The ASFF Resource.Type should be `AwsResourceAccessManagerShare`
    - Resource Access Manager: Check if any RAM shares share to external principals by using the GetResourceShares API. The ASFF Resource.Type should be `AwsResourceAccessManagerShare`
    - Kinesis Data Analytics: Check if KDA Applications log to CloudWatch using the DescribeApplication API, if `CloudWatchLoggingOptionDescriptions` returns an empty list then the check fails. The ASFF Resource.Type should be `AwsKinesisDataAnalyticsApplication`
    - **Multiple** CloudFront: Check the distros for multiple types of configurations (ActiveTrustedSigners, Origin HTTPS only, TLS 1.2 Only support for Origins, Viewer Protocol HTTPS/Redirect HTTPS, Logging, GeoRestrictions, WAF Assocation, TLS 1.2 ViewerCert). All checks use the GetDistrobution API.

**Nice to Have**
N/A

**Additional Information**
N/A

**Comment by jonrau1** [comment]
@brandypeterson I could not assign you directly

**Comment by brandypeterson** [comment]
@jonrau1 for Resource Access Manager checks, I think we are mostly concerned with SELF-owned shares, though it might be interesting to look at FAILED shares for externally-owned shares.

**Comment by jonrau1** [comment]
@brandypeterson that is a good thought too - definitely well within the misconfig territory
