### ISSUE TITLE
[KinesisAnalytics.1] Applications should log to CloudWatch not getting assessed

### ISSUE THREAD

**Issue by nimbus1212** [jonrau1/ElectricEye#53]
**Describe the bug**
**[KinesisAnalytics.1] Applications should log to CloudWatch** is not getting assessed with the error message showing `AWS region us-east-1 not supported for kinesisanalyticsv2`, because supported regions is returning an empty list. AWS Kinesis Analytics is supported in this region and also if logging is not configured then `"CloudWatchLoggingOptionDescriptions"` key is not present which gives keyError. It should be handle in try exception. In the exception block, we can pass the finding. 

**To Reproduce**
1. Run the assessment and check for [KinesisAnalytics.1]

**Expected behavior**
[KinesisAnalytics.1] Applications should log to CloudWatch control should have a finding.

**Screenshots**

**Logs**
Any stack traces, error reports, CloudTrail logs, etc.

**Additional context**

**Comment by nimbus1212** [comment]
With `kinesisanalyticsv2`, supported regions don't get listed with `aws ssm get-parameters-by-path   --path /aws/service/global-infrastructure/services/kinesisanalyticsv2/regions`. This is the reason why this control is not giving any finding. The supported regions can be enumerated with `kinesisanalytics`.
![image](https://user-images.githubusercontent.com/26418487/112437818-5dd31b80-8d6d-11eb-8c73-dd42d808444a.png)

**Comment by jonrau1** [comment]
Fixed with https://github.com/jonrau1/ElectricEye/commit/b118f59c452b8b77c71c16c44d56172200cd6793, will be in the next PR for #58

**Comment by jonrau1** [comment]
Complete with #64
