### ISSUE TITLE
Parameter Validation Failed while writing output to Security Hub 

### ISSUE THREAD

**Issue by rpatkialbelli** [jonrau1/ElectricEye#67]
**Describe the bug**
When the scan is completed the issues are pushed to Security Hub but recently there are errors thrown around parameters validation failure which leads to none of the issues sent to Security Hub.

**To Reproduce**
1. Setup ECS task (Fargate) or run via Cloudshell - python3 eeauditor/controller.py
2. When the scan finishes the writing of results to Security Hub initiates 
3. Error is thrown with parameter validation failed

**Expected behavior**
Successfull scan results pushed to Security Hub

**Logs**
Writing 376 results to SecurityHub
Error writing output: Parameter validation failed:
Unknown parameter in Findings[9].Resources[0].Details.AwsEc2Instance: "**AmiAge**", must be one of: Type, ImageId, IpV4Addresses, IpV6Addresses, KeyName, IamInstanceProfileArn, VpcId, SubnetId, LaunchedAt, NetworkInterfaces
Unknown parameter in Findings[10].Resources[0].Details.AwsEc2Instance: "**AmiStatus**", must be one of: Type, ImageId, IpV4Addresses, IpV6Addresses, KeyName, IamInstanceProfileArn, VpcId, SubnetId, LaunchedAt, NetworkInterfaces
Done.

**Additional context**
For testing purpose I removed Amazon_EC2_Auditor but again error is thrown for **"Other"** parameter (must be oneof:aws Type, Id, Partition, Region, ResourceRole, Tags, DataClassification, Details) which is present in almost all auditors.
Errors are thrown in the console when running via Cloud Shell or can be found in Cloudwatch when using ECS task.
The scan outputs are successfull for csv and json but error occurs only for Security Hub

**Comment by rpatkialbelli** [comment]
@jonrau1 - Please let me know if you need more details

**Comment by jonrau1** [comment]
@rpatkialbelli sorry on the HUGE delay on this - was investigating and got distracted with other stuff.

Working another feature right now and trying to run down the Resource.Other error, I found the other AMI ones so far.
