### ISSUE TITLE
Revamp the format of a failed finding at Slack and Teams

### ISSUE THREAD

**Issue by kbhagi** [jonrau1/ElectricEye#74]
**Story**
The current format of markdown at Slack and Teams make it harder to read a message. As a Security / DevOps / Infra Engineer of ElectricEye, I want to see a failed finding to be neatly formatted with an header containing sections. 

**Definition of Done**
- Use of Slacks' rich message layouts consisting of block kit layout blocks and block elements a failed findings has been revamped. 
- Use of Teams message cards consisting of facts and sections
- A screenshot of a failed finding at Slack 
![SlackFinding1](https://user-images.githubusercontent.com/19756773/141778608-86ea81f2-5ba8-492d-b64f-bd481bbd28d1.png)
- A screenshot of a failed finding at Teams
 ![TeamsFindings1](https://user-images.githubusercontent.com/19756773/141778614-1bdea89d-9573-453e-b533-62daf1c67c36.png)

- An updated working python code that pushes findings to Slack and Teams [Source Code](https://gist.github.com/kbhagi/dd024d0a310bc31e04b3564065f6276f)

**Nice to Have**
 For each of the failed finding I would like to either remediate or suppress with a click of a button followed by an instant feedback at the same Slack message to know the status of remediation or suppression.  Given that there is a one-2-one mapping between a failed findings and its remediation.  As a part of my college project,  I have built the feature using Slack's outgoing webhooks, SNS , API Gateway, Lambda, SSM Automation Documents and RDS MySQL.  Then tested it through clicking the remediate and suppress buttons at Slack. Check the screenshots below to know more.
![SlackRemediation](https://user-images.githubusercontent.com/19756773/141779306-f7963d50-3c09-4b94-a9ab-e08233caec75.png)
![SlackSuppression](https://user-images.githubusercontent.com/19756773/141779309-35675471-0ebd-4cb1-b371-f1ddccd175c9.png)
I would also like to built the same for the Teams message

**Additional Information**
Slack : Creating rich message layouts - https://api.slack.com/messaging/composing/layouts
MSFT Teams : https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference

**Comment by jonrau1** [comment]
Complete with #75
