### ISSUE TITLE
No findings for custom AWS AppStream 2.0 Images

### ISSUE THREAD

**Issue by GulshirulIslam** [jonrau1/ElectricEye#78]
**Describe the bug**
When AWS account is scanned, AWS managed appstream images are only present in the report and the ones which are user created i.e, custom appstream images are ignored during the scan.

**To Reproduce**
1. Create sample Appstream images in the AWS account.
2. Scan the account using electric eye.
3. Check EE report, only AWS managed Appstream images can be found and not the created appstream image.

**Expected behavior**
EE scans and there should be findings for all appstream images and not only for AWS managed ones.

**Comment by jonrau1** [comment]
Taking a look

**Comment by jonrau1** [comment]
> **Describe the bug** When AWS account is scanned, AWS managed appstream images are only present in the report and the ones which are user created i.e, custom appstream images are ignored during the scan.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Create sample Appstream images in the AWS account.
> 2. Scan the account using electric eye.
> 3. Check EE report, only AWS managed Appstream images can be found and not the created appstream image.
> 
> **Expected behavior** EE scans and there should be findings for all appstream images and not only for AWS managed ones.

Can you try the change pushed to the `fixes` branch (commit https://github.com/jonrau1/ElectricEye/commit/b2f85d98eddcdb6fcb9c221ee4123a9f75e73fdc) if I am reading the docs correctly taking out the filter for PUBLIC/PRIVATE/SHARED should default to all of them. I don't have any AS2.0 images of my own to test w/ fast
