### ISSUE TITLE
CloudFormation Auditor cannot be parsed in Arn format

### ISSUE THREAD

**Issue by wild0ni0n** [jonrau1/ElectricEye#92]
**Problem**
As a result of executing AWS_CloudFormation_Auditor, the values o `Id`, `GeneratorId`, and `Resource[Id]`  cannot be parsed in Arn format.

**To Reproduce**

Execute the following command

```
$ python3 eeauditor/controller.py -a AWS_CloudFormation_Auditor -o stdout

Running ElectricEye in AWS Region ap-northeast-1.
 Located in Partition aws.
 Profile AWS Account is ■■■■■■■■.
 Profile current IAM principal ARN is arn:aws:sts::■■■■■■■■:assumed-role/■■■■■■■■/■■■■■■■■
Executing Check: cfn_drift_check
Executing Check: cfn_monitoring_check
{"SchemaVersion": "2018-10-08", "Id": "arn:aws:cloudformation:ap-northeast-1:■■■■■■■■:stack/■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■/arn:aws:cloudformation:ap-northeast-1:■■■■■■■■:stack/■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■/■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■/cloudformation-drift-check", "ProductArn": "arn:aws:securityhub:ap-northeast-1:■■■■■■■■:product/■■■■■■■■/default"
...
```
An arn-formatted string is output twice for the value of `Id`.

**Expected behavior**

The `stackArn` variable is used for `Id`, `GeneratorId`, and `Resource[Id]` in AWS_CloudFormation_Auditor.py, respectively.
The `stackArn` variable uses `stackId`, and since `stackId` is an Arn format string, the Arn format string is repeated in the output.

Assign the `stackId` to the `stackArn` variable. Alternatively, it is preferable not to include `stackId` in `stackArn`.

**Comment by jonrau1** [comment]
Okay, I see what I did, I was "creating" an ARN not realized `StackId` actually returns the ARN. Opening a PR now.
