### ISSUE TITLE
Can it work with mattermost?

### ISSUE THREAD

**Issue by mihai-satmarean** [jonrau1/ElectricEye#96]
Very nice feature,
Can it work with mattermost?
best regards

**Comment by jonrau1** [comment]
@mihai-satmarean I have not used Mattermost - but it should not be too hard to adapt one of the forwarders for Pagerduty, Teams or Slack for it if it's simply just a JSON API

**Comment by jonrau1** [comment]
Closing this for now. Feel free to re-open if you want to submit a PR. I likely won't have any time to test / do it
